version: "3"
services:
  dolar-comercial-api:
    build: .
    ports:
      - "8080:8080"
    networks:
      - rede-cotacao-api
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.0.4
    networks:
      - rede-cotacao-api
    ports:
    - 27017:27017
    expose:
      - '27017'
    container_name: cotacaodb
networks:
  rede-cotacao-api:
    driver: bridge
